application: smitfuel
version: 3
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /.*
  script: fuel.py

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
